server:
  port: 8080
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/parkingSystem
    username: root
    password: root
  mvc:
   view:
    prefix: /WEB-INF/View/
    suffix: .jsp